config/routes.rb
Rails.application.routes.draw do
  get 'users/set_student' => 'users#set_student'

  post 'users/update_student' => 'users#update_student'

  resources :school_classes do
    member do
      get 'delete_from_class'
    end
  end

  resources :subjects

  resources :degrees

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'welcome/index'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :student, class_name: "User", foreign_key: "tutor_id"

  belongs_to :tutor, class_name: "User"
  belongs_to :student_class, class_name: "SchoolClass"
  has_many :degrees, class_name: "Degree", foreign_key: "student_id"

  has_one :teacher_class, class_name: "SchoolClass", foreign_key: "teacher_id"
  has_many :subjects, class_name: "Subject", foreign_key: "teacher_id"

  validates :name, presence: true
  validates :surname, presence: true
  validates :personal_id, presence: true
  validates :personal_id, length: {is:11}
  validates :personal_id, numericality: true

  after_initialize :set_not_approved

  enum role: [:teacher, :student, :tutor, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    "#{name} #{surname}"
  end

  def degrees_by_subject(subject_id)
    degrees.where(:subject_id => subject_id)
  end

private
  def set_not_approved
    self.is_approved ||= false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :valid_is_admin, except: [:set_student, :update_student]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  def set_student
    @users = User.where(:role => 1)
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def update_student
    User.find(params[:user][:student]).update(:tutor_id => current_user.id)
    current_user.update(:is_approved => false)
    redirect_to root_path, notice: @language.student_set
  end

  # PATCH/PUT /users/1'You cannot delete yourself.'
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: @language.user_updated }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.id == current_user.id
      respond_to do |format|
        format.html { redirect_to users_url, alert: @language.self_destroy }
        format.json { render :show, status: :ok, location: @user }
      end
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: @language.user_deleted }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :personal_id, :role, :is_approved)
    end

    def valid_is_admin
      if current_user.role != 'admin'
        redirect_to root_path, alert: @language.missing_admin_rights
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label @language.name
    .controls
      = f.text_field :name, class: 'form-control', required: true
  .form-group
    = f.label @language.surname
    .controls
      = f.text_field :surname, class: 'form-control', required: true
  .form-group
    = f.label @language.email
    .controls
      = f.text_field :email, class: 'form-control', required: true
  .form-group
    = f.label @language.personal_id
    .controls
      = f.text_field :personal_id, class: 'form-control', required: true
  .form-group
    = f.label @language.role
    .controls
      = f.select(:role, {@language.student  => 'student',
                         @language.teacher  => 'teacher',
                         @language.tutor    => 'tutor',
                         @language.admin    => 'admin'})
  .form-group
    = f.label @language.is_approved
    .controls
      = f.check_box :is_approved
  .actions
    = f.submit @language.update, :class => 'btn btn-primary'
    = link_to @language.back, users_path, :class => 'btn btn-default'

app/views/users/edit.html.haml
.page-header
    %h1= @language.editing_user

= render 'form'

app/views/users/index.html.haml
%div.navbar.navbar-default
  .container
    %div.navbar-header
      .navbar-toogle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    %div.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active= link_to @language.users, users_path
        %li= link_to @language.classes, school_classes_path
        %li= link_to @language.subjects, subjects_path
        %li= link_to @language.degrees, degrees_path

%table.table.table-striped
  %thead
    %tr
      %th= @language.name
      %th= @language.surname
      %th= @language.email
      %th= @language.personal_id
      %th= @language.role
      %th= @language.is_approved
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.surname
        %td= user.email
        %td= user.personal_id
        %td
          = @language.roles[user.role]
          - if user.role == 'tutor' and user.student
            = ' ('
            = link_to user.student.full_name, user_path(user.student)
            = ')'
        %td
          = form_for user, :remote => true do |f|
            = f.check_box :is_approved, :class => 'submittable'
        %td
          = link_to @language.show, user, :class => 'btn btn-default btn-xs'
          = link_to @language.edit, edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to @language.delete_account, user, :method => :delete, :data => { :confirm => @language.sure },
                                                    :class => 'btn btn-danger btn-xs', :style => 'color: white;'

app/views/users/set_student.html.haml
%br
= form_tag(:method => 'post', :controller => 'users', :action => 'update_student') do
  .field
    = collection_select :user, :student, @users, :id, :full_name
  .actions
    = submit_tag @language.update, :class => 'btn btn-primary', :style => 'color: white;'

app/views/users/show.html.haml
.page-header
  %h1
    .label.label-default= @language.roles[@user.role]
    = @user.full_name

%p
  %b= @language.personal_id + ':'
  = @user.personal_id
%p
  %b= @language.email + ':'
  = @user.email
%p
  %b= @language.is_approved + ':'
  = @language.approved[@user.is_approved]
- if @user.role == 'tutor' and @user.student
  %p
    %b= @language.student + ':'
    = @user.student.full_name
- elsif @user.role == 'student' and @user.tutor
  %p
    %b= @language.tutor + ':'
    = @user.tutor.full_name

= link_to @language.edit, edit_user_path(@user), :class => 'btn btn-default'
= link_to @language.back, users_path, :class => 'btn btn-default'