config/routes.rb
Rails.application.routes.draw do
  get 'users/set_student' => 'users#set_student'

  post 'users/update_student' => 'users#update_student'

  resources :school_classes do
    member do
      get 'delete_from_class'
    end
  end

  resources :subjects

  resources :degrees

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'welcome/index'

  root 'welcome#index'

end

app/models/degree.rb
class Degree < ActiveRecord::Base
  belongs_to :subject
  belongs_to :student, class_name: "User"
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: [:show, :edit, :update, :destroy]
  before_action :set_degree_service, only: [:create]
  before_action :authenticate_user!
  before_filter :valid_is_approved

  respond_to :html

  def index
    @degrees = Degree.all
    if current_user.role == 'admin'
      @subjects = Subject.all
      @classes  = SchoolClass.all
    elsif current_user.role == 'teacher'
      @subjects = current_user.subjects
      @classes  = current_user.subjects.map{ |subject| subject.school_class }.uniq
    elsif current_user.role == 'student'
      @subjects = current_user.student_class.subjects
      @classes  = [current_user.student_class]
    else
      @subjects = current_user.student.student_class.subjects
      @classes  = [current_user.student.student_class]
    end

    respond_with(@degrees)
  end

  def show
    if current_user.role == 'student' and @degree.student_id != current_user.id
      redirect_to degrees_path, alert: @language.missing_rights
    elsif current_user.role == 'tutor' and @degree.student_id != current_user.student.id
      redirect_to degrees_path, alert: @language.missing_rights
    elsif current_user.role == 'teacher' and @degree.subject.teacher.id != current_user.id
      redirect_to degrees_path, alert: @language.missing_rights
    else
      respond_with(@degree)
    end
  end

  def new
    @subject = Subject.find(params[:subject_id])
    if current_user.role == 'admin' or (current_user.role == 'teacher' and @subject.teacher.id == current_user.id)
      @degrees = Array.new(@subject.school_class.students.count) {DegreeForm.new}
      if @degrees.length > 0
        respond_with(@degree)
      else
        redirect_to edit_school_class_path(@subject.school_class), alert: @language.add_students
      end
    else
      redirect_to degrees_path, alert: @language.missing_rights
    end
  end

  def edit
    @subject = Subject.find(@degree.subject_id)
    if current_user.role == 'admin' or (current_user.role == 'teacher' and @subject.teacher.id == current_user.id)
      @degrees = [@degree]
    else
      redirect_to degrees_path, alert: @language.missing_rights
    end
  end

  def create
    if @degree_service.call(filled_degrees_forms)
      redirect_to degrees_path
    else
      redirect_to new_degree_path(:subject_id => params[:subject_id]),
                  :alert => @language.degrees_errors
    end
  end

  def update
    if current_user.role == 'admin' or (current_user.role == 'teacher' and @degree.subject.teacher.id == current_user.id)
      @degree.update(degree_params)
      respond_with(@degree)
    else
      redirect_to degrees_path, alert: @language.missing_rights
    end
  end

  def destroy
    if current_user.role == 'admin' or (current_user.role == 'teacher' and @degree.subject.teacher.id == current_user.id)
      @degree.destroy
      respond_with(@degree)
    else
      redirect_to degrees_path, alert: @language.missing_rights
    end
  end

  private
    def set_degree
      @degree = Degree.find(params[:id])
    end

    def degree_params
      params.require(:degree).permit(:value, :activity, :description)
    end

    def set_degree_service
      @degree_service = DegreeService.new
    end

    def valid_is_approved
      if current_user.is_approved != true
        redirect_to root_path, alert: @language.not_approved
      end
    end

    def filled_value_from_params
      params[:degrees].select{ |key, degree| degree[:value] != '' }
    end

    def filled_degrees_forms
      degrees = Array.new

      filled_value_from_params.each do |degree|
        degrees.push(DegreeForm.new(value:       degree[1][:value],
                                    description: degree[1][:description],
                                    activity:    params[:activity],
                                    student_id:  degree[1][:student_id],
                                    subject_id:  params[:subject_id]))
      end
      degrees
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_form.html.haml
%p
  %b= @language.class + ':'
  = @subject.school_class.name

%p
  %b= @language.subject + ':'
  = @subject.name

%p
  %b= @language.teacher + ':'
  = @subject.teacher.full_name

%br

= form_tag degrees_path do
  - for degree in @degrees
    - if degree.errors.any?
      #error_explanation
        %h2= "#{pluralize(degree.errors.count, "error")} prohibited this degree from being saved:"
        %ul
          - degree.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = label_tag @language.activity
    .controls
      = text_field_tag :activity, @degrees[0].activity, class: 'form-control', required: true
      = hidden_field_tag :subject_id, @subject.id

  %table.table.table-striped
    %thead
      %tr
        %th= @language.name
        %th= @language.surname
        %th= @language.degree
        %th= @language.description

    %tbody
      - @degrees.each_with_index do |degree, i|
        %tr
          - if action_name == 'new'
            %td= @subject.school_class.students[i].name
            %td= @subject.school_class.students[i].surname
          - else
            %td= @degrees[i].student.name
            %td= @degrees[i].student.surname

          = fields_for "degrees[#{i}]" do |f|
            %td{align: :center}
              .value_column
                = f.text_field :value, :value => @degrees[i].value
            %td
              .description_column
                = f.text_area :description, :value => @degrees[i].description
                = f.hidden_field :student_id, :value => @subject.school_class.students[i].id

  .actions
  = submit_tag @language.update, :class => 'btn btn-primary'
  = link_to @language.back, degrees_path, :class => 'btn btn-default'

app/views/degrees/edit.html.haml
.page-header
  %h1= @language.edit_degree

= render 'form'

app/views/degrees/index.html.haml
%div.navbar.navbar-default
  .container
    %div.navbar-header
      .navbar-toogle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse'}
        - if current_user.role == 'admin'
          %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    %div.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if current_user.role == 'admin'
          %li= link_to @language.users, users_path
        %li= link_to @language.classes, school_classes_path
        %li= link_to @language.subjects, subjects_path
        %li.active= link_to @language.degrees, degrees_path

- if current_user.role == 'admin' or current_user.role == 'teacher'
  %center
    %h4= @language.choose_subject

    %form{:action => new_degree_path, :method => :get}
      = select_tag :subject_id, options_for_select(@subjects.map { |subject| [subject.name_with_class, subject.id] })
      .actions
      = submit_tag @language.insert_degrees, :name => nil, :class => 'btn btn-primary'

  %br

- for school_class in @classes
  .panel.panel-info
    %center.panel-heading
      %b.panel-title= school_class.name

    .panel-body
      - for subject in school_class.subjects & @subjects
        .panel.panel-default
          %center.panel-heading
            .panel-title= subject.name

          .panel-body
            %table.table.table-striped
              %thead
                %tr
                  %th= @language.name
                  %th= @language.surname
                  %th= @language.degrees

              %tbody
                - for student in school_class.permitted_students(current_user)
                  %tr
                    %td= student.name
                    %td= student.surname
                    %td
                      - for degree in student.degrees_by_subject(subject.id)
                        = link_to degree.value, degree
                        - if current_user.role == 'admin' or current_user.role == 'teacher'
                          = link_to @language.edit, edit_degree_path(degree), :class => 'btn btn-default btn-xs'
                          = link_to @language.delete, degree, :method => :delete, :class => 'btn btn-danger btn-xs',
                                                      :style => 'color: white;', :data => { :confirm => @language.sure }

app/views/degrees/new.html.haml
.page-header
  %h1= @language.insert_degrees

= render 'form'

app/views/degrees/show.html.haml
.page-header
  %h1
    .label.label-default= @language.degree
    = @degree.value

%p
  %b= @language.subject + ':'
  = @degree.subject.name
%p
  %b= @language.teacher + ':'
  = @degree.subject.teacher.full_name
%p
  %b= @language.activity + ':'
  = @degree.activity
%p
  %b= @language.description + ':'
  = @degree.description
%p
  %b= @language.created + ':'
  = @degree.created_at

= link_to @language.edit, edit_degree_path(@degree), :class => 'btn btn-default'
= link_to @language.back, degrees_path, :class => 'btn btn-default'