config/routes.rb
Rails.application.routes.draw do
  get 'users/set_student' => 'users#set_student'

  post 'users/update_student' => 'users#update_student'

  resources :school_classes do
    member do
      get 'delete_from_class'
    end
  end

  resources :subjects

  resources :degrees

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'welcome/index'

  root 'welcome#index'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :school_class
  belongs_to :teacher, class_name: "User"
  has_many :degrees, dependent: :destroy

  validates :name, presence: true, length: { in: 2..30 }

  def name_with_class
    "#{name}, #{school_class.name}"
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :assign_subjects
  before_filter :valid_is_approved

  respond_to :html

  def index
    respond_with(@subjects)
  end

  def show
    if @subjects.include?(@subject)
      respond_with(@subject)
    else
      redirect_to subjects_path, alert: @language.missing_rights
    end
  end

  def new
    if current_user.role != 'admin' and current_user.role != 'teacher'
      redirect_to subjects_path, alert: @language.missing_rights
    else
      @subject = Subject.new
      if params.include?(:school_class_id)
        @classes  = SchoolClass.where(:id => params[:school_class_id])
      else
        @classes = SchoolClass.all
      end
      if current_user.role == 'admin'
        @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      elsif current_user.role == 'teacher'
        @teachers = [current_user]
      end

      respond_with(@subject)
    end
  end

  def edit
    if current_user.role == 'student' or current_user.role == 'parent' or !@subjects.include?(@subject)
      redirect_to subjects_path, alert: @language.missing_rights
    else
    @classes = SchoolClass.all
      if current_user.role == 'admin'
        @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      elsif current_user.role == 'teacher'
        @teachers = [current_user]
      end
    end
  end

  def create
    if current_user.role != 'admin' and current_user.role != 'teacher'
      redirect_to subjects_path, alert: @language.missing_rights
    else
      @subject = Subject.new(subject_params)
      @classes = SchoolClass.all
      if current_user.role == 'admin'
        @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      elsif current_user.role == 'teacher'
        @teachers = [current_user]
      end

      @subject.save
      respond_with(@subject)
    end
  end

  def update
    if current_user.role == 'student' or current_user.role == 'parent' or !@subjects.include?(@subject)
      redirect_to subjects_path, alert: @language.missing_rights
    else
      @classes = SchoolClass.all
      if current_user.role == 'admin'
        @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      elsif current_user.role == 'teacher'
        @teachers = [current_user]
      end

      @subject.update(subject_params)
      respond_with(@subject)
    end
  end

  def destroy
    if current_user.role == 'student' or current_user.role == 'parent' or !@subjects.include?(@subject)
      redirect_to subjects_path, alert: @language.missing_admin_rights
    else
      @classes = SchoolClass.all
      if current_user.role == 'admin'
        @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      elsif current_user.role == 'teacher'
        @teachers = [current_user]
      end

      @subject.destroy
      respond_with(@subject)
    end
  end

  private
    def set_subject
      @subject = Subject.find(params[:id])
    end

    def subject_params
      params.require(:subject).permit(:name, :teacher_id, :school_class_id)
    end

    def valid_is_approved
      if current_user.is_approved != true
        redirect_to root_path, alert: @language.not_approved
      end
    end

    def assign_subjects
      if current_user.role == 'admin'
        @subjects = Subject.all
      elsif current_user.role == 'teacher'
        @subjects = current_user.subjects
      elsif current_user.role == 'tutor'
        @subjects = current_user.student.student_class.subjects
      else
        @subjects = current_user.student_class.subjects
      end
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.haml
= form_for @subject do |f|
  - if @subject.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subject.errors.count, "error")} prohibited this subject from being saved:"
      %ul
        - @subject.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label @language.subject_name
    .controls
      = f.text_field :name, class: 'form-control', required: true
  .form-group
    = f.label @language.teacher
    .controls
      = f.collection_select :teacher_id, @teachers, :id, :full_name
  .form-group
    = f.label @language.class
    .controls
      = f.collection_select :school_class_id, @classes, :id, :name
  .actions
    = f.submit @language.update, :class => 'btn btn-primary'
    = link_to @language.back, subjects_path, :class => 'btn btn-default'

app/views/subjects/edit.html.haml
.page-header
  %h1= @language.edit_subject

= render 'form'

app/views/subjects/index.html.haml
%div.navbar.navbar-default
  .container
    %div.navbar-header
      .navbar-toogle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse'}
        - if current_user.role == 'admin'
          %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    %div.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if current_user.role == 'admin'
          %li= link_to @language.users, users_path
        %li= link_to @language.classes, school_classes_path
        %li.active= link_to @language.subjects, subjects_path
        %li= link_to @language.degrees, degrees_path

%table.table.table-striped
  %thead
    %tr
      %th= @language.subject_name
      %th= @language.class
      %th= @language.teacher
      %th

  %tbody
    - @subjects.each do |subject|
      %tr
        %td= subject.name
        %td= subject.school_class.name
        %td= subject.teacher.full_name
        %td
          = link_to @language.show, subject, :class => 'btn btn-default btn-xs'
          - if current_user.role == 'admin' or current_user.role == 'teacher'
            = link_to @language.edit, edit_subject_path(subject), :class => 'btn btn-default btn-xs'
            = link_to @language.insert_degrees, {:controller => 'degrees', :action => 'new', :subject_id => subject.id},
                                                  :class => 'btn btn-default btn-xs'
            = link_to @language.delete, subject, :method => :delete, :data => { :confirm => @language.sure },
                                                  :class => 'btn btn-danger btn-xs', :style => 'color: white;'

- if current_user.role == 'admin' or current_user.role == 'teacher'
  = link_to @language.new_subject, new_subject_path, :class => 'btn btn-primary', :style => 'color: white;'

app/views/subjects/new.html.haml
.page-header
  %h1= @language.new_subject

= render 'form'

app/views/subjects/show.html.haml
.page-header
  %h1
    .label.label-default= @language.subject
    = @subject.name
%p
  %b= @language.teacher + ':'
  = @subject.teacher.full_name
%p
  %b= @language.class + ':'
  = @subject.school_class.name

= link_to @language.edit, edit_subject_path(@subject), :class => 'btn btn-default'
= link_to @language.back, subjects_path, :class => 'btn btn-default'