config/routes.rb
Rails.application.routes.draw do
  get 'users/set_student' => 'users#set_student'

  post 'users/update_student' => 'users#update_student'

  resources :school_classes do
    member do
      get 'delete_from_class'
    end
  end

  resources :subjects

  resources :degrees

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/school_classes_controller.rb
class SchoolClassesController < ApplicationController
  before_action :set_school_class, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :assign_school_classes
  before_filter :valid_is_approved

  respond_to :html

  def index
    respond_with(@school_classes)
  end

  def show
    if current_user.role == 'tutor'
      @students = @school_class.students & [current_user.student]
    else
      @students = @school_class.students
    end
    if @school_classes.include?(@school_class)
      respond_with(@school_class)
    else
      redirect_to school_classes_path, alert: @language.missing_rights
    end
  end

  def new
    if current_user.role != 'admin'
      redirect_to school_classes_path, alert: @language.missing_admin_rights
    else
      @school_class = SchoolClass.new
      @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      @students = User.where("role = ? AND is_approved = ?", 1, true)

      respond_with(@school_class)
    end
  end

  def edit
    if current_user.role == 'student' or current_user.role == 'parent' or !@school_classes.include?(@school_class)
      redirect_to school_classes_path, alert: @language.missing_rights
    else
      @students = User.where("role = ? AND is_approved = ?", 1, true)
      if current_user.role == 'admin'
        @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      elsif current_user.role == 'teacher'
        @teachers = [current_user]
      end
    end
  end

  def create
    if current_user.role != 'admin'
      redirect_to school_classes_path, alert: @language.missing_admin_rights
    else
      @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      @students = User.where("role = ? AND is_approved = ?", 1, true)
      @school_class = SchoolClass.new(school_class_params)

      @school_class.save
      for student_id in params[:school_class][:students][1..-1]
        User.update(student_id, :student_class_id => @school_class.id)
      end
      respond_with(@school_class)
    end
  end

  def update
    if current_user.role == 'student' or current_user.role == 'parent' or !@school_classes.include?(@school_class)
      redirect_to school_classes_path, alert: @language.missing_rights
    else
      @students = User.where("role = ? AND is_approved = ?", 1, true)
      if current_user.role == 'admin'
        @teachers = User.where("role = ? AND is_approved = ?", 0, true)
      elsif current_user.role == 'teacher'
        @teachers = [current_user]
      end

      @school_class.update(school_class_params)
      for student_id in params[:school_class][:students][1..-1]
        User.update(student_id, :student_class_id => params[:id])
      end
      respond_with(@school_class)
    end
  end

  def destroy
    if current_user.role != 'admin'
      redirect_to school_classes_path, alert: @language.missing_admin_rights
    else
      @school_class.destroy
      respond_with(@school_class)
    end
  end

  def delete_from_class
    school_class = SchoolClass.find(params[:class])
    if current_user.role == 'student' or current_user.role == 'parent' or !@school_classes.include?(school_class)
      redirect_to school_classes_path, alert: @language.missing_rights
    else
      User.update(params[:student_id], :student_class_id => nil)
      redirect_to school_class_path(params[:class]), notice: @language.deleted_from_class
    end
  end

  private
    def set_school_class
      @school_class = SchoolClass.find(params[:id])
    end

    def school_class_params
      params.require(:school_class).permit(:name, :teacher_id)
    end

    def valid_is_approved
      if current_user.is_approved != true
        redirect_to root_path, alert: @language.not_approved
      end
    end

    def assign_school_classes
      if current_user.role == 'admin'
        @school_classes = SchoolClass.all
      elsif current_user.role == 'teacher'
        @school_classes = [current_user.teacher_class]
      elsif current_user.role == 'student'
        @school_classes = [current_user.student_class]
      else
        @school_classes = [current_user.student.student_class]
      end
    end
end

app/helpers/school_classes_helper.rb
module SchoolClassesHelper
end

app/views/school_classes/_form.html.haml
= form_for @school_class do |f|
  - if @school_class.errors.any?
    #error_explanation
      %h2= "#{pluralize(@school_class.errors.count, "error")} prohibited this school_class from being saved:"
      %ul
        - @school_class.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label @language.class
    .controls
      = f.text_field :name, class: 'form-control', required: true
  .form-group
    = f.label @language.educator
    .controls
      = f.collection_select :teacher_id, @teachers, :id, :full_name
  .form-group
    = f.label @language.add_students
    .controls
      = f.collection_select(:students, @students, :id, :full_name,
                                            {}, {:multiple => true, :size => 10})
  .actions
    = f.submit @language.update, :class => 'btn btn-primary', :style => 'color: white;'
    = link_to @language.back, school_classes_path, :class => 'btn btn-default'

app/views/school_classes/edit.html.haml
.page-header
  %h1= @language.edit_class

= render 'form'

app/views/school_classes/index.html.haml
%div.navbar.navbar-default
  .container
    %div.navbar-header
      .navbar-toogle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse'}
        - if current_user.role == 'admin'
          %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    %div.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if current_user.role == 'admin'
          %li= link_to @language.users, users_path
        %li.active= link_to @language.classes, school_classes_path
        %li= link_to @language.subjects, subjects_path
        %li= link_to @language.degrees, degrees_path

%table.table.table-striped
  %thead
    %tr
      %th= @language.class
      %th= @language.educator
      %th

  %tbody
    - @school_classes.each do |school_class|
      %tr
        %td= school_class.name
        %td= school_class.teacher.full_name
        %td
          = link_to @language.show, school_class, :class => 'btn btn-default btn-xs'
          - if current_user.role == 'admin' or current_user.role == 'teacher'
            = link_to @language.edit, edit_school_class_path(school_class), :class => 'btn btn-default btn-xs'
            = link_to @language.add_subject, {:controller => 'subjects', :action => 'new',
                                              :school_class_id => school_class.id}, :class => 'btn btn-default btn-xs'
          - if current_user.role == 'admin'
            = link_to @language.delete, school_class, :method => :delete, :data => { :confirm => @language.sure },
                                                      :class => 'btn btn-danger btn-xs', :style => 'color: white;'

- if current_user.role == 'admin'
  = link_to @language.new_class, new_school_class_path, :class => 'btn btn-primary', :style => 'color: white;'

app/views/school_classes/new.html.haml
.page-header
  %h1= @language.new_class

= render 'form'

app/views/school_classes/show.html.haml
.page-header
  %h1
    .label.label-default= @language.class
    = @school_class.name

%p
  %b= @language.educator + ':'
  = @school_class.teacher.full_name

.panel.panel-default
  .panel-heading
    .panel-title= @language.students
  .panel-body
    %table.table.table-striped
      %thead
        %tr
          %th= @language.name
          %th= @language.surname
          %th= @language.email
          - if current_user.role == 'admin' or current_user.role == 'teacher'
            %th= @language.personal_id
            %th

      %tbody
        - for student in @students
          %tr
            %td= student.name
            %td= student.surname
            %td= student.email
            - if current_user.role == 'admin' or current_user.role == 'teacher'
              %td= student.personal_id
              %td= link_to @language.delete_from_class, {:controller => 'school_classes', :action => 'delete_from_class',
                                                          :student_id => student.id, :class => @school_class},
                                                          :class => 'btn btn-danger btn-xs', :style => 'color: white;'

= link_to @language.edit, edit_school_class_path(@school_class), :class => 'btn btn-default'
= link_to @language.back, school_classes_path, :class => 'btn btn-default'